title: Стандарт
optionalCategoryIndex: true
supportedLanguages:
  - ru
properties:
  - name: Раздел
    type: Flag
    style: green
    icon: book-up
language: ru
description: Стандарт информационного моделирования "Моспроект"
style: blue
logo: bim (1).png
